# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        carre: #nom du filtre
            quality: 100 #qualité de l'image
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: outbound
        echelle:
            quality: 100
            filters:
                upscale:
                    min: [100, 100]
                thumbnail:
                    size: [100, 100]
                    mode: outbound
        description:
            quality: 100
            filters:
                upscale:
                    min: [300, 300]
                thumbnail:
                    size: [300, 300]
                    mode: outbound

